version: '3'

services:
  graphql:
    build:
      context: .
      args:
        - NODE_ENV=development
    ports:
      - "80:4000"
    environment:
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=toor
      - MONGO_HOSTNAME=db
      - MONGO_PORT=27017
      - MONGO_DATABASE_NAME=gpql
    volumes:
      - .:/usr/src/app
      - notused:/usr/src/app/node_modules
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
      - configdb:/data/configdb

volumes:
  notused:
  configdb:
