version: '3'

services:
  graphql:
    build:
      context: .
      args:
        - NODE_ENV=development
    ports:
      - "80:4000"
    env_file:
      - dev.local.env
    volumes:
      - .:/usr/src/app
      - notused:/usr/src/app/node_modules
    depends_on:
      - db

  db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=toor
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
      - configdb:/data/configdb

volumes:
  notused:
  configdb:
